#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/setup/html-theme-readtheorg.setup
#+Title: Methods: Python programming for economists
#+Author: Jan Boone
#+LANGUAGE: en
#+INFOJS_OPT: view:showall toc:t ltoc:t mouse:underline path:http://orgmode.org/org-info.js
#+LaTeX_CLASS: article-12
#+LATEX_HEADER: \renewcommand{\floatpagefraction}{.8} %% avoids figures getting their own page
#+latex_header: \input{author.tex}
#+latex_engraved_theme: t
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+OPTIONS: toc:nil num:2 timestamp:nil ':t \n:nil @:t ::t |:t ^:{} _:{} *:t TeX:t LaTeX:t
#+HTML_HEAD: <link rel="stylesheet" href="./css/Latex.css">
#+HTML_HEAD: <link rel="stylesheet" href="https://latex.now.sh/prism/prism.css">
#+HTML_HEAD: <script src="https://cdn.jsdelivr.net/npm/prismjs/prism.min.js"></script>
#+HTML_HEAD: <style>
#+HTML_HEAD: pre.src code {
#+HTML_HEAD:   background: transparent !important;
#+HTML_HEAD:   border: none !important;
#+HTML_HEAD:   box-shadow: none !important;
#+HTML_HEAD:   padding: 0 !important;
#+HTML_HEAD: }
#+HTML_HEAD: pre.src-python code {
#+HTML_HEAD:   font-size: 1.1em !important;
#+HTML_HEAD: }
#+HTML_HEAD: </style>
#+EXPORT_EXCLUDE_TAGS: noexport

This website contains the material for the MSc course Methods: Python programming for economists.

**This website is under construction for 2026/2027**

This year the course is taught by:
+ Jan Boone
+ Mery Ferrando
+ Joyce Ladenstein

------------
#+TOC: headlines 2

-------

* Course Material
  :PROPERTIES:
  :CUSTOM_ID:       material
  :END:

** Career Development part of the course

Career development activities (workshops and career events) are part of the course ‘Methods: Python Programming’. The goal of this career development part of the course is to help students from the Master Economics transition into their careers after graduation. The focus is on personal growth and development and provides practical tools to be well prepared for the job application process.

In both semester 1 and semester 2, workshop(s) will be offered by Student Career Services. To pass the course ‘Methods: Python Programming’, you must participate in at least 1 workshop of your choice and at least 1 career event. You will receive a partial grade once you have completed the Python programming part of the course. At the end of the academic year, you will be assessed whether you have met the set criteria of the career development part of the course through a pass or fail. Only with a positive grade for the Python programming part of the course and a pass for the career development part of the course you have passed the course ‘Methods: Python Programming’.

For more information and for an overview of workshops and career events offered throughout the year check the [[https://tilburguniversity.instructure.com/courses/17415/modules][‘Career Development for MSc Economics’ Canvas page]] and [[file:img/Syllabus_Career_Development_2026_2027.pdf][this file]].



** Python part
For the Python part of the course, there are three types of materials that we use:
- the [[https://janboone.github.io/Methods_python_for_economists_lectures/][website with the lectures]]
- the (free) book by [cite/text/c:@downey-2023-model-simul-python]
- [[https://app.datacamp.com/][Datacamp]]

*** The lectures (mandatory)

The [[https://janboone.github.io/Methods_python_for_economists_lectures/][website with the lectures]] are mandatory. Make sure you read the material before each lecture (see [[#lecture_schedule][lecture schedule]] below) and solve the Review Questions at the end of each Lecture.

Learning a programming language requires you to try and program yourself. Just copying the code during the lectures is not going to help you very much; if you are only doing this, it is basically a waste of your time.

The important part of this course you do at home going over the lectures, experimenting with the code and trying to solve the Review Questions. This part will most likely be frustrating because you get errors and you make mistakes (i.e. different results than you would expect) etc. Don't worry, this is normal when you are learning a programming language!

*** [cite:@downey-2023-model-simul-python] (highly recommended)

The lectures are (loosely) based on [cite/text/c:@downey-2023-model-simul-python] which is a great introduction into Python. The book can be found [[https://greenteapress.com/wp/modsimpy/][here]] and the associated notebooks [[https://allendowney.github.io/ModSimPy/][here]]. The book sometimes uses "wrappers" around the Python functions that we will be using and it is targeted at engineering students. But it does explain the idea of modelling in Python very well and it gives you an introduction to =numpy= and =scipy= functions.

*** Datacamp (optional)

If you have never done any programming before, the three courses below from Datacamp will help you get up to speed. I recommend that you do these courses before the start of the semester. If you have programmed before or done some Datacamp courses already, this part is optional.

You can get access to Datacamp via the [[https://www.tilburguniversity.edu/students/skills/programming][university website]].

From Datacamp, you can do the following courses:

+ Intro: [[https://www.datacamp.com/courses/intro-to-python-for-data-science]]
+ Intermediate: [[https://www.datacamp.com/courses/intermediate-python-for-data-science]]
+ Pandas: https://learn.datacamp.com/courses/data-manipulation-with-pandas

These courses teach you the basic Python syntax. In our lectures we use parts of Python more specific to economics; e.g. commands to solve equations, equilibria etc. These parts of the course complement each other. It is not the case that all the Python that we use in the lectures, you will first see in Datacamp but most of it is in Allen Downey's book.

Most students like Datacamp to get used to Python syntax. A minority of students really dislike Datacamp. If you do not like it either, you can also read [[https://greenteapress.com/wp/think-python-3rd-edition/][Think Python]] as an introduction to "pure" Python (instead of Downey's modeling and simulation book, mentioned above). You can buy the book or read the free online version. The jupyter notebooks can be found on [[https://github.com/AllenDowney/ThinkPython/tree/v3][github]]. You can clone this repository and work with the notebooks. You can also find some wonderful presentations on Youtube by the author Allen Downey.


*** TODO Questions :noexport:
- also add Joyce's syllabus to the chatbot: https://chatbot.tilburg.ai/chat
- add index.pdf
- add gender economics template

You can ask questions to the [[https://programmingforeconomists.tilburgai.nl/][chatbot]]
  + note that this is still experimental (no rights can be derived etc. etc.)
  + give us your feedback to improve the chatbot

*** TODO example final assignent :noexport:
In September there is a lecture on gender economics. In the lecture Mery will discuss some papers on this topic. There is a notebook where the models discussed are simulated in Python. This notebook is then discussed in a following lecture. The notebook will teach you something about gender economics and Python. At the same time, it shows you what we expect you to do in the final assignment for this course: take an existing theory paper and solve the model in Python and simulate outcomes of the model.

* Lecture schedule
   :PROPERTIES:
   :CUSTOM_ID:       lecture_schedule
   :END:

|       date |                time | staff | room         | [[https://janboone.github.io/Methods_python_for_economists_lectures/][lecture]] | Downney |
|------------+---------------------+-------+--------------+---------+---------|
| 2026-08-26 |         12:45-14:30 | Joyce | Cube 219     |         |         |
| 2026-09-01 |         12:45-14:30 | Jan   | Cube 219     |       1 |     1-4 |
| 2026-09-08 |         12:45-14:30 | Mery  | Cube 219     |         |         |
| 2026-09-15 |         12:45-14:30 | Jan   | Cube 217     |       2 |     5-8 |
| 2026-10-12 |         12:45-14:30 | Joyce | Cube 17      |         |         |
| 2026-10-14 |         14:45-16:30 | Joyce | Cube 213     |         |         |
| 2026-10-21 |         08:45-10:30 | Jan   | CZ 112       |       3 |   11-14 |
| 2026-10-28 |         14:45-16:30 | Joyce | Cube 21      |         |         |
| 2026-11-04 |         12:45-14:30 | Joyce | E 4 Blackbox |         |         |
| 2026-11-11 |         08:45-10:30 | Jan   | MKZ 111      |       4 |         |
| 2026-11-19 |         08:45-10:30 | Jan   | MKZ 111      |       5 |         |
| 2026-11-25 |         10:45-12:30 | Jan   | CZ 9         |       6 |         |
| 2026-12-02 |         10:45-12:30 | Jan   | Cube 220     |     Q&A |         |
| 2027-01-04 | deadline assignment |       |              |         |         |
| 2027-05-10 |      deadline resit |       |              |         |         |



** First Lecture

[[file:./Introduction_Lecture.org::#introduction][Introduction Lecture]]

*** Initial Assignment
    :PROPERTIES:
    :CUSTOM_ID:       initial_assignment
    :END:

Do the following three steps:
+ create a github account on [[https://github.com/][github]] (you need this account to submit your final assignment)
  + we advise you to do this before **Thursday September 25, 2025**
+ go to
  + [[https://jupyterlab.uvt.nl/][jupyter lab]]
    + IT suggests that you use the Firefox browser to access jupyter lab
    + sometimes it helps to access jupyter lab with an incognito/private window
    + or --if all else fails-- you can use [[https://colab.research.google.com/][google's colab]]
+ create a new python notebook and type the following code in the first cell:
#+BEGIN_SRC shell
%%bash

git clone https://github.com/janboone/Python-programming-for-economists.git
#+END_SRC
+ then press the Shift key and Enter key at the same time
+ this creates a folder on the server `Python-programming-for-economists` that contains the material for the course.
+ Note: you can only run this command once. If you run it again, you get an error since the folder already exists.
+ If you want to see the final assignment in jupyter lab, you can also type:
#+BEGIN_SRC shell
%%bash

git clone https://github.com/janboone/python_assignments
#+END_SRC

- you can view the final assignment in this repository: https://github.com/janboone/python_assignments
- instructions for the assignment can be found below.


- create marimo on jupterlab: [[file:img/Start_Marimo.pdf][how-to]]

** Deadlines
   :PROPERTIES:
   :CUSTOM_ID: Deadlines
   :END:

- The deadline for the *final python assignment* is: Monday January 4th, 2027. 
- The resit deadline for the python assignment is: Monday May 10th, 2027.
- Your grade is determined by:
  - a "pass" on the Career Services assignments;
  - final assignment.

Follow the instructions below and on Canvas explaining how to submit an assignment and fill in the google form etc.

Also note the rules for the resit of the final assignment in case you submitted an assignment for the first exam opportunity (you cannot do an app on the same paper/model twice for your assignment).


* Assignments

For this course there is one final assignment. 

Note that you can do the assignment alone or with at max. one other student (i.e. max group size is 2).

** TODO Submitting assignments :noexport:
- github or gitlab???
  
The final assignment is submitted using github classroom:
- on Canvas we will give you the link to the github repos. with the assignment notebook;
- instructions on how to work with github classroom can be found [[file:./Manual_students.pdf][here]]
- to submit your assignment:
  + do not change the name of the assignment notebook
  + when you submit your final assignment, fill in the google form where the link to the form is on Canvas
  + push the assignment notebook to your team's github classroom repository


** TODO Instructions for submitting final assignment to be put on Canvas :noexport:

**2026/7**: are we going to use github classroom or gitlab.uvt???

*** relevant links:

**** TODO each year renew classroom links for the new year
- [X] set deadline in github classroom
- [ ] add github classroom assignment with the template repos. for 2025/6:
  - https://forms.gle/4oaPJ2APQArAQrzx9
  - https://classroom.github.com/classrooms/16413080-tisem-python-for-economists/assignments/assignments-2025-2026
  - invite link: https://classroom.github.com/a/AJx5NX7k


**** TODO google form
- [ ] create google form for students to fill in once they finish assignment: https://forms.gle/4oaPJ2APQArAQrzx9 (this is the link for 2025/2026)
- [ ] in the google form adjust the format of the assignment address for the new year
- [ ] change link to the classroom assignment and google form below

- instructions are attached to website (no need to repeat on Canvas): [[file:~/Google Drive/repositories/github/websites/github_classroom_assignments/how_to_use_nbgrader_github_classroom/Manual_students.pdf]]
- show uploading assignment to github classroom during lecture

*** Canvas

**** TODO copy/paste on Canvas

Dear students,

The link for the python assignment (template) is: https://classroom.github.com/a/AJx5NX7k (this is the link for 2025/2026)

You can do the assignment on your own or with (at max.) one other student. 

When you use the link to the assignment, you will be asked for your team's name. Choose your favorite name!

When you finish your assignment:

1. download your assignment (jupyter notebook) from jupyter lab (or google colabs; or check where it is on your computer when using anaconda) to your computer (e.g. in the folder Downloads)

2. push it onto your assignment's github repository using github classroom web interface

3. fill in the following google form: https://forms.gle/4oaPJ2APQArAQrzx9 (note 1: you need to be logged in with your @tilburguniversity.edu account to access the form; note 2: you only need to fill in the google form once).

We need the information from the google form to link your assignment to your student number which is needed for the exam administration.

If you have questions about the assignment or the procedure described above, create an issue on the webpage at: https://github.com/janboone/Python-programming-for-economists/issues

Then you can see whether other students had the same question (which was already answered) or fellow-students can learn from your question. These issues can be read by anyone, so do not provide any privacy related information.

Good luck with the assignment,

Jan.


** Final Assignment
  :PROPERTIES:
  :CUSTOM_ID: final_assignment
  :END:


- for the deadlines of the final assignment, see [[Deadlines]] above

** what we are looking for

The idea of the final assignment is that you report on an economic model in a transparent way that can easily be verified/reproduced by others. Think of yourself in, say, two years time where you work in a company, bank, consultancy firm or ministry. You need to explain an economic "phenomenon" to your colleagues. Since not all your colleagues are necessarily economists, your goal is to create an interactive (marimo) app. With this app, colleagues can figure out themselves how certain parameters affect the outcome and how sensitive outcomes are to (other) parameter values.

Since future colleagues is a bit vague, think of the intended audience as your fellow students. They should be able to understand the code you write, together with the explanations that you give for this code and for the economics that you are explaining.

The following ingredients will be important when we evaluate your final assignment:
+ The *topic* for the app should come from a *theory* (i.e. not empirical) paper or a theoretical model that you have seen in class for another course
+ Briefly describe what the paper/model does and what the results are that you want to illustrate with the app
+ When you use information (e.g. a literature reference), create a (Markdown) link to this information. The reader then only needs to click to find the relevant information.
+ Then formulate a clear and transparent *research question* that the user will be able to answer using the app
+ Briefly *motivate* why this question is interesting.
+ Use $\LaTeX$ to introduce and explain the *model*. Describe the main equations (using $\LaTeX$) of the model that you will program in Python.
+ Explain how you move from the analytical equations of the paper to Python code.
+ We will be looking for at the least the following methods in the code:
  + code is interactive, e.g. using sliders,
  + there agents maximizing payoffs; in the Python code make sure you use *optimization methods*,
  + solve for an *equilibrium* using Python (with fixed points),
  + use a parameter sweep (and pandas to store the results) to show how the results are affected by parameter values.
+ Explain your code in Markdown blocks, not as comments in code blocks
  + and note that these explanations make sense in both the edit and app views of the marimo notebook
+ Present interactive graphs of your simulation results using =matplotlib= and marimo sliders
+ Discuss what the figures show (e.g. $x$ is increasing in $y$) and explain the economic intuition for this relation (between $x$ and $y$).
+ What can the user learn from the app and the interactive outcomes that follow from it

Remark 1:
+ you can copy code from the web or an LLM; but
  + make sure that you explain the code that you use so that another student of the course understands it and can use it;
  + e.g. if you use functions, libraries that we have not used in the lectures you need to explain these in your notebook
  + explain special syntax like =f(*my_list)= if you use constructs like this
  + but there is no need to explain what =np.arange= does: we use this extensively in class
  + give the reference of the code that you copy or acknowledge the use of an LLM
  + check the code and explain the economics of your results yourself; do not rely on the [[file:LLM.org][LLM]] only.

Remark 2:
+ the apps we create in the lectures do actually not satisfy the criteria for the final assignment:
+ either there is no optimization problem that is solved with python (e.g. in the Cournot example we derived the reaction functions analytically)
+ or there is no equilibrium derived like in the Solow model app
+ the app based on the gender economics lecture does have all the elements that we are looking for in the final assignment

*** TODO improve explanation :noexport:

Suggestions for improving the assignment description

1. Make the grading criteria more explicit
Right now the ingredients are clear, but students will optimize for what is graded. A rubric helps.

Example breakdown:
- Economic motivation and research question: 10%
- Correct explanation of theory/model: 20%
- Translation from equations to code: 20%
- Equilibrium computation and optimization: 15%
- Interactive app design and usability: 15%
- Interpretation of results/economic intuition: 15%
- Transparency/reproducibility/citations: 5%

This signals that explanation and understanding matter at least as much as coding.

2. Explicitly require a “model-to-code mapping”
This is one of the best ways to detect understanding.

Add a required subsection:
- “From equations to code”
  - For each key equation:
    - write the equation,
    - explain the economic meaning,
    - explain how it is implemented computationally,
    - identify the numerical method used.

Example:
- “Equation (3) defines equilibrium price as a fixed point. In Python we implement this using scipy.optimize.fixed_point because…”

Students who merely paste code struggle here.


6. Clarify acceptable use of LLMs
Currently this is permissive but vague. Make expectations operational.

Example:
“You may use LLMs as coding assistants, but:
- you must understand and explain all code submitted;
- all externally generated code must be acknowledged;
- inability to explain submitted code during follow-up questions may result in grade penalties;
- copied code without adaptation or explanation is considered poor academic practice.”


Suggestions for improving the template


4. Include a validation section
Require students to verify known analytical cases.

Example:
- “Check whether the numerical equilibrium matches the analytical solution when parameter α = 0.”

This is excellent for discouraging blind code use.

5. Add structure for parameter sweeps
Right now only sliders are emphasized. Add an explicit requirement for systematic analysis.

Example:
#+begin_src python
results = pd.DataFrame(...)
#+end_src
Then ask students to:
- summarize trends,
- identify nonlinearities,
- discuss robustness.

6. Encourage modular coding
Require at least:
- one function for payoffs,
- one function for equilibrium,
- one simulation function.

This improves readability and exposes whether students understand decomposition.


2. Require “why this method?” explanations
Not:
- “we used scipy.optimize”

But:
- “we use root-finding because equilibrium is implicitly defined…”


9. Penalize unexplained sophistication
State explicitly:
- “Using advanced libraries/methods without explanation will not increase grades.”

This removes incentives to paste impressive but opaque code.

One important broader point

If the assignment mainly rewards “a working app,” LLM use becomes almost impossible to distinguish from understanding. But if the assignment rewards:
- explanation,
- economic reasoning,
- numerical interpretation,
- validation,
- extension,
then LLMs become useful tools rather than substitutes for learning.

That is the equilibrium you probably want.



** resit of final assignment

The resit of the final assignment needs to start from a new paper/model compared to the one you handed in before. Simply adjusting your first submission based on our feedback will be not be enough.

Otherwise, follow the procedure above on how to submit the assignment and fill in the google form. 


* Bibliography
#+cite_export: csl ./chicago-author-date.csl
#+bibliography:~/Nextcloud2/Literature/references.bib
#+print_bibliography:
