#+title: Career Development part of Methods: Python Programming for Economists
#+author: Joyce Ladenstein, Career Services Officer Master Economics 

**This page is under construction for 2024/2025** 

- J.Y.M.Ladenstein [at] tilburguniversity.edu
- Office hours: Upon appointment
- Canvas page with more information: Career Development Economics:
  - https://tilburguniversity.instructure.com/courses/13424 

* Goal  

The goal of the career development part of the course Methods: Python Programming for Economists is to help students from the Master Economics transition into their careers after graduation. The focus of the course is on personal growth and development and provides practical tools to be well prepared for the job application process. 

* Description  

In both semester 1 and semester 2, workshop(s) will be offered by Student Career Services. Participation in the workshop 'Finding purpose: Discover a fulfilling and impactful future' in semester 1 (consisting of 2 sessions) is optional (according to own needs). Participation in at least 1 workshop of your choice in semester 2 is mandatory. In addition, participation in at least 1 career event of your choice organized by Asset-Economics during the year is mandatory. 

* Kick-off session 

kick-off sessions of the course are planned at the beginning of each semester to give new students more information about the career development part of the course Methods: Python Programming for Economists. 


* Workshops 

** Semester 1 (blok 2): 

Students can choose (according to own needs) to follow the workshop: 'Finding purpose: Discover a fulfilling and impactful future' spread over 2 sessions (participation in both is required) organized by Student Career Services. 

- The 1st session lasts 2.5 hours as we kick off the session by an interactive session with 2 economists/ alumni sharing their purpose story for inspiration. 
- The 2nd session lasts 2 hours and takes place approximately 3 weeks after the 1st session. 
- 3 weeks prior to the 1st session students must have registered via Canvas so we know how many groups there are and how many trainers are needed. 

*** Assignments: 
- In preparation for the workshop, students fill out the VIA Character Strengths Survey and complete a small preparatory assignment. They take the outcome to the 1st session of the workshop.  
- After the first session, participants are given an interim assignment. They take the outcome to the 2nd session of the workshop.  
- If students need it, they can take advantage of the opportunity to receive 1 hour of 1-on-1 coaching from an experienced career coach from Student Career Services in addition to the workshop. 

** Semester 2 (blok 4): 

Students choose at least one of the following practical workshops organized by Student Career Services (mandatory): 
- Unlock Success: Master your assessment with expert preparation!   
- Empower your potential: Elevate your personal effectiveness today!  
- PitchPower: Mastering the art of real-life branding 
- CareerReady: Ace your job interview 
- Connecting futures: How to use LinkedIn 

3 weeks prior to the workshops students must have registered via Canvas so we know how many groups there are and how many trainers are needed. 

*** Preparation assignments

- In preparation of the workshop ‘PitchPower: Mastering the art of real-life branding’, students complete the Career Academy's online Canvas module "elevator pitch’’. The outcome is not immediately reviewed by Student Career Services afterwards. Students take the outcome to the workshop and continue working with it during the workshop (deepening). 
- In preparation of the workshop ‘Connecting futures: How to use LinkedIn', students complete the Career Academy's online Canvas module "LinkedIn’’. The outcome is not immediately reviewed by Student Career Services afterwards. Students take the outcome to the workshop and continue working with it during the workshop (deepening). 

* Career Events 

Students participate in at least one of the following career events organized by Asset-Economics (mandatory) during the year: 
- Inside the Business Day 
- Economist in a world of data 
- Economics Dinner 
- Talent Day 
- Business Data Challenge 

Registration via the website of Asset-Economics. 

* Grading 

The workshops and career events are part of the course ‘Methods: Python Programming for Economists’. To pass the course, you must participate in at least 1 workshop of your choice in semester 2 and 1 career event in semester 1 or 2. You will receive a partial grade once you have completed the Python programming part of the course. At the end of the academic year, you will be assessed whether you have met the set criteria of the career development part of the course through a pass or fail. Only with a positive grade for the Python programming part of the course and a pass for the career development part of the course you have passed the course ‘Methods: Python Programming for Economists’.

** Resit 

If there are special circumstances that prevent you from attending 1 of the mandatory workshops in semester 2 or 1 Asset-Economics career event throughout the year, please contact TiSEM Career Services, tisem.careerservices@uvt.nl, for an alternative assignment. 

 

* Appendix 1 Content of the workshops 

** Finding purpose: Discover a fulfilling and impactful future (2 sessions, 1 of 2,5 hour and 1 of 2 hours)  

Unlock the key as a start to a more purpose-driven life! Join this interactive workshop, where you'll embark on a journey of self-discovery, and chart your course toward a fulfilling and purposeful future. 

 

** Unlock Success: Master Your Assessment with Expert Preparation!  

In addition to the experience of completing a valid personality questionnaire and achieving the results, you will learn:
- What exactly an assessment is, how do you prepare, and what types of assessments exist? 
- Which competencies are considered essential by the employer How to remove a review day can be seen?  
- What different capacity tests, practical simulations, models, and instruments are available (reinventing assessments)? 
- What the Big Five means in relation to the personality questionnaire. Through the Big Five personality test, organizations want to gain insight into the character and personality of the applicant? 
- Achieve your test results and how you can move forward with them.  
- How to Prepare for The Interview & Expanding the STARR Method. 


** Empower your potential: Elevate your personal effectiveness today! 

This workshop is aimed at developing skills and behavior that lead to personal success and effectiveness. Themes such as taking responsibility, increasing the influence of your actions on your own life and that of others, proactivity and goal setting are some of the components we will delve into in more detail. In short, you learn how to get behind the wheel of your own life (again).  

 

** PitchPower: Mastering the art of real-life branding 

What makes you unique and how do you present your unique ‘I-brand’. How are you going to use this in your search for a job? At the end of this workshop, you have defined your personal brand, and you know how to show it while networking on- and offline in search for a job. 

 
** CareerReady: Ace your job interview 

After this workshop, you know what is expected from you during a job interview and you can present yourself well. 

** Connecting futures: How to use LinkedIn 

This workshop will provide you with tips on how you can use LinkedIn to find a job, connect with interesting people and companies. 

  

* Appendix 1 Content of the Career Events 

- Inside the Business Day 
- Economist in a world of data 
- Economics Diner 
- Talent Day 
- Business Data Challenge 

 

 
